// <auto-generated />
using System;
using AttendanceManagementSystem.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AttendanceManagementSystem.Infrastructure.Migrations
{
    [DbContext(typeof(TimeSheetDbContext))]
    [Migration("20240723002004_Initial-schema")]
    partial class Initialschema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("AttendanceManagementSystem.Domain.Entity.Employee", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CardNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("AttendanceManagementSystem.Domain.Entity.Log", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CurrentEmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<uint>("TimeShift")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CurrentEmployeeId");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("AttendanceManagementSystem.Domain.Entity.UserAccount", b =>
                {
                    b.Property<int>("UserAccountID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserAccounctOfEmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("UserAccountID");

                    b.HasIndex("UserAccounctOfEmployeeId")
                        .IsUnique();

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("AttendanceManagementSystem.Domain.Entity.Log", b =>
                {
                    b.HasOne("AttendanceManagementSystem.Domain.Entity.Employee", "Employee")
                        .WithMany("Logs")
                        .HasForeignKey("CurrentEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("AttendanceManagementSystem.Domain.Entity.UserAccount", b =>
                {
                    b.HasOne("AttendanceManagementSystem.Domain.Entity.Employee", "Employee")
                        .WithOne("UserAccount")
                        .HasForeignKey("AttendanceManagementSystem.Domain.Entity.UserAccount", "UserAccounctOfEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("AttendanceManagementSystem.Domain.Entity.Employee", b =>
                {
                    b.Navigation("Logs");

                    b.Navigation("UserAccount");
                });
#pragma warning restore 612, 618
        }
    }
}
